### ISSUE TITLE
Leader board error

### ISSUE THREAD

**Issue by lstone01** [Drustcraft/Drustcraft-API#6]
There is an issue with loading the leader board. 

You can recreate it by opening the leader board.

Images
![Leaderboard error](https://user-images.githubusercontent.com/89302307/130543190-20d9ba62-79fb-4484-9e39-abc9c8d18242.PNG)

**Comment by nomadjimbob** [comment]
The API is referencing game tables that no longer exist. This will be updated in the code to provide a quick patch until #1 is implemented. The Website interface will also need to be updated as it references Emeralds or Currency which is no longer tracked.

Note that there is also a large delay in collating the data.
